### ISSUE TITLE
Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by OR13** [godspeed20/mui-editable-table#4]
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

using ` "react": "15.3.2" `

I played games trying to figure out if it was a dependency / version issue, but gave up when everything started breaking. 

Pretty sure this explains what you will need to do to resolve this issue if you can repro it: https://facebook.github.io/react/warnings/refs-must-have-owner.html

**Comment by godspeed20** [comment]
Thanks for that, will take a look and try to rectify it asap

**Comment by godspeed20** [comment]
Had a play, looks like the issue is actually more the end comment on that help page - my plugin required react 15.4.0 and up whereas you were using an exact version, so you ended up with two react version in your codebase (I tested both cases and got your error when I switched my example to your exact react version only). I've downgraded the react version to 15.3.0 and up and it seems to work in my tests, can you try it again and see if it resolves your issue please?

**Comment by godspeed20** [comment]
Closing this as I haven't heard back. if you still have this issue let me know and i'll look into it again. thank you
